name: Test-tomsway
favicon: null
layout_spectrum: 0.044598828069865704
typography_spectrum: 0.08078209706582129
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.47620023996569216
  lightness: 0.8413135714363307
  saturation: 0.9249433351214975
  rhythmicContrast: 0.936015237821266
purpose: []
